version: '3.8'

services:
  vosk-server:
    build:
      context: ./vosk-server
      dockerfile: Dockerfile
    container_name: vosk-server
    hostname: vosk-server
    volumes:
      - ./vosk-server/models:/opt/vosk-models
    networks:
      - custom_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:2700/"]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 3600s  # 1 hour for first-time model download (~13GB)
    deploy:
      resources:
        limits:
          memory: 4G

  libretranslate:
    image: libretranslate/libretranslate:latest
    container_name: libretranslate
    hostname: libretranslate
    environment:
      - LT_LOAD_ONLY=en,es,ja,pt,ru,fr,de,nl,it
      - LT_THREADS=4
    volumes:
      - libretranslate-data:/home/libretranslate/.local
    networks:
      - custom_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python3", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:5000/languages', timeout=5)"]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 600s  # 10 minutes for model loading
    deploy:
      resources:
        limits:
          memory: 2G

  dependency-checker:
    image: curlimages/curl:latest
    container_name: dependency-checker
    hostname: dependency-checker
    command: sh -c "while true; do sleep 10; done"
    networks:
      - custom_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "sh", "-c", "curl -f http://vosk-server:2700/ && curl -f http://libretranslate:5000/languages"]
      interval: 5s
      timeout: 5s
      retries: 1
      start_period: 3600s

  web-service:
    build:
      context: ./web-service
      dockerfile: Dockerfile
    container_name: auto-caption-web
    hostname: auto-caption-web
    ports:
      - "${WEB_SERVICE_PORT:-9080}:8000"
    environment:
      - DEEPL_API_KEY=${DEEPL_API_KEY}
      - VOSK_SERVER_URL=http://vosk-server:2700
      - LIBRETRANSLATE_URL=http://libretranslate:5000
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
    volumes:
      - ${UNRAID_MEDIA_PATH}:/data
    networks:
      - custom_network
    depends_on:
      dependency-checker:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  custom_network:
    external: true
    name: ${DOCKER_NETWORK:-auto-caption-network}

volumes:
  libretranslate-data:
