version: '3.8'

services:
  vosk-server:
    build:
      context: ./vosk-server
      dockerfile: Dockerfile
    container_name: vosk-server
    hostname: vosk-server
    volumes:
      - ./vosk-server/models:/opt/vosk-models
    networks:
      - auto-caption-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:2700/"]
      interval: 60s
      timeout: 10s
      retries: 10
      start_period: 3600s  # 1 hour for first-time model download (~13GB)
    deploy:
      resources:
        limits:
          memory: 4G

  libretranslate:
    image: libretranslate/libretranslate:latest
    container_name: libretranslate
    hostname: libretranslate
    environment:
      - LT_LOAD_ONLY=en,es,ja,pt,ru,fr,de,nl,it
      - LT_THREADS=4
    volumes:
      - libretranslate-data:/home/libretranslate/.local
    networks:
      - auto-caption-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 120s
    deploy:
      resources:
        limits:
          memory: 2G

  web-service:
    build:
      context: ./web-service
      dockerfile: Dockerfile
    container_name: auto-caption-web
    hostname: auto-caption-web
    ports:
      - "${WEB_SERVICE_PORT:-9080}:8000"
    environment:
      - DEEPL_API_KEY=${DEEPL_API_KEY}
      - VOSK_SERVER_URL=http://vosk-server:2700
      - LIBRETRANSLATE_URL=http://libretranslate:5000
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
    volumes:
      - ${UNRAID_MEDIA_PATH}:/data
    networks:
      - auto-caption-network
    depends_on:
      vosk-server:
        condition: service_healthy
      libretranslate:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  auto-caption-network:
    external: true
    name: ${DOCKER_NETWORK:-auto-caption-network}

volumes:
  libretranslate-data:
