version: '3.8'

services:
  whisper-server:
    build:
      context: ./whisper-server
      dockerfile: Dockerfile
    container_name: whisper-server
    hostname: whisper-server
    volumes:
      - ./whisper-server/models:/opt/models
    networks:
      - custom_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:2800/"]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 600s  # 10 minutes for first-time model download (~3GB for large-v3)
    deploy:
      resources:
        limits:
          memory: 8G
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  libretranslate:
    image: libretranslate/libretranslate:latest
    container_name: libretranslate
    hostname: libretranslate
    environment:
      - LT_LOAD_ONLY=en,es,ja,pt,ru,fr,de,nl,it
      - LT_THREADS=4
    volumes:
      - libretranslate-data:/home/libretranslate/.local
    networks:
      - custom_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python3", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:5000/languages', timeout=5)"]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 600s  # 10 minutes for model loading
    deploy:
      resources:
        limits:
          memory: 2G

  dependency-checker:
    image: curlimages/curl:latest
    container_name: dependency-checker
    hostname: dependency-checker
    command: sh -c "while true; do sleep 10; done"
    networks:
      - custom_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "sh", "-c", "curl -f http://whisper-server:2800/"]
      interval: 5s
      timeout: 5s
      retries: 1
      start_period: 600s

  web-service:
    build:
      context: ./web-service
      dockerfile: Dockerfile
    container_name: auto-caption-web
    hostname: auto-caption-web
    ports:
      - "${WEB_SERVICE_PORT:-9080}:8000"
    environment:
      - WHISPER_SERVER_URL=http://whisper-server:2800
      - LIBRETRANSLATE_URL=http://libretranslate:5000
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
    volumes:
      - ${UNRAID_MEDIA_PATH}:/data
    networks:
      - custom_network
    depends_on:
      dependency-checker:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  custom_network:
    external: true
    name: plex_network

volumes:
  libretranslate-data:
